name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t test4 .

    - name: Run image
      run: docker run -d -p 888:88 test4 sh

    - name: Run tests
      run: |
        curl -s http://localhost:888 | grep -q "<h1>" && echo "Found <h1> tag" || echo "No <h1> tag found"