name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t test4 .

    - name: Run tests
      run: docker run -d -p 888:88 test4 sh

    - name: Run tests
      run: |
        curl -X POST \
        -H "Content-Type: text/html" \
        --data-binary @/usr/share/nginx/html/index.html \
        http://localhost:888