name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t test4 .

    - name: Run tests
      run: docker run -d -p 8020:88 test sh -c "curl localhost:8020"

    - name: Log test results
      run: docker logs test4
